using System.Globalization;

namespace SharpGenerator;

public static class VersionInfo
{
    public const string ToolName = "LibGodotSharp SharpGenerator";
    public static string Version = DateTime.UtcNow.ToString("u", CultureInfo.InvariantCulture);

    public const string AutoGeneratedDocComment = """
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
""";
}
